### ISSUE TITLE
Remove device login Auth 

### ISSUE THREAD

**Issue by niedbalski** [calyptia/core-docker-desktop-extension#73]
Calyptia authentication uses auth0 which works fine. But when is about to authenticate external applications like the Docker Desktop extension we depend on a Devide-based authentication mechanism that adds an extra step for the user.

Talking with the authors of Meshery, they mention they are using this Golang component to implement a straight OAuth2 layer:

- https://github.com/markbates/goth

can we host that service ? the good thing is that goth seems to allow to use Auth0 as the backend

**Comment by nicolasparada** [comment]
Here is some findings...

To be able to use the authorization code grant flow you need a `redirect_uri` which is an URI that the browser can access to.

With the docker extensions you can have a backend running in a VM. By default, the backend runs on the docker socket, and you can call it directly from the UI using the SDK .

Now, the UI doesn't have a URL so we cannot use the UI as `redirect_uri` (`docker-desktop://dashboard/open` only opens the docker-extension dashboard).
Then, since the backend is running in a unix socket, we don't have an `http:` address to redirect to either.

There is another option. You can make the backend to run on a port, let's say `3000`. And expose this port on the host. Now we have a URL at `http://localhost:3000` we can use as `redirect_uri`.
The only problem with this approach is that the user might be already running something on port `3000` and the extension will fail to load.

You might think we could only `expose` the port in the docker-compose file and leave a random port to be assigned on the host, but that won't work since we need to know the `redirect_uri` from ahead since it needs to be allowed in the authorization server.

Also, allowing `localhost` is a bad idea in terms of security since now anyone can create a client, and also doesn't run securely on `https`.

I guess the device code flow was thought exactly to solve these problems 😕

**Comment by nicolasparada** [comment]
CC @edsiper

**Comment by nicolasparada** [comment]
Btw I took a look at the source-code of other extensions. And either they use the same device code flow, or they do it wrongly by exposing the client secret in the extension...
Or they don't use oauth2 and have a classic direct username-password login (which in our case would mean to change everything).

**Comment by nicolasparada** [comment]
We are blocked on this until a future release of docker desktop.
They are working on allowing a redirect to the UI ;)

> we have some items in our backlog to allow redirecting directly to the extension UI (as you mention, this is more inline with oauth2 general flow)

**Comment by edsiper** [comment]
thanks
